/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: "hsl(var(--card))",
                "card-foreground": "hsl(var(--card-foreground))",
                popover: "hsl(var(--popover))",
                "popover-foreground": "hsl(var(--popover-foreground))",
                primary: "hsl(var(--primary))",
                "primary-foreground": "hsl(var(--primary-foreground))",
                secondary: "hsl(var(--secondary))",
                "secondary-foreground": "hsl(var(--secondary-foreground))",
                muted: "hsl(var(--muted))",
                "muted-foreground": "hsl(var(--muted-foreground))",
                accent: "hsl(var(--accent))",
                "accent-foreground": "hsl(var(--accent-foreground))",
                destructive: "hsl(var(--destructive))",
                "destructive-foreground": "hsl(var(--destructive-foreground))",
                success: "hsl(var(--success))",
                "success-foreground": "hsl(var(--success-foreground))",
                warning: "hsl(var(--warning))",
                "warning-foreground": "hsl(var(--warning-foreground))",
                "focus-star": "hsl(var(--focus-star))",
                "focus-star-outline": "hsl(var(--focus-star-outline))",
                info: "hsl(var(--info))",
                "info-foreground": "hsl(var(--info-foreground))",
                "status-inbox": "hsl(var(--status-inbox))",
                "status-next": "hsl(var(--status-next))",
                "status-waiting": "hsl(var(--status-waiting))",
                "status-someday": "hsl(var(--status-someday))",
                "status-reference": "hsl(var(--status-reference))",
                "status-done": "hsl(var(--status-done))",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                // Additive M3 roles, only defined so far for `focus-dark`/`focus-light`
                // (see index.css) — registered here so `bg-tertiary`, `text-dnd`, etc. actually
                // generate a utility class; every other theme leaves these vars unset and falls
                // back through the cascade like any other unset custom property.
                "surface-container": "hsl(var(--surface-container))",
                "surface-container-high": "hsl(var(--surface-container-high))",
                "on-surface-variant": "hsl(var(--on-surface-variant))",
                tertiary: "hsl(var(--tertiary))",
                "tertiary-foreground": "hsl(var(--tertiary-foreground))",
                "outline-variant": "hsl(var(--outline-variant))",
                "secondary-container": "hsl(var(--secondary-container))",
                "secondary-container-foreground": "hsl(var(--secondary-container-foreground))",
                dnd: "hsl(var(--dnd))",
                "dnd-foreground": "hsl(var(--dnd-foreground))",
            },
        },
    },
    plugins: [],
}
